models.py
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from sqlalchemy.orm import relationship

db = SQLAlchemy()

# ユーザー
class User(UserMixin, db.Model):
    # テーブル名
    __tablename__ = 'users'
    # ID（PK）
    id = db.Column(db.Integer, primary_key=True)
    # ユーザー名
    username = db.Column(db.String(50), unique=True, nullable=False)
    # パスワード
    password = db.Column(db.String(120), nullable=False)
    # パスワードをハッシュ化して設定する
    def set_password(self, password):
        self.password = generate_password_hash(password)
    # 入力したパスワードとハッシュ化されたパスワードの比較
    def check_password(self, password):
        return check_password_hash(self.password, password)

class URLList(db.Model):
    __tablename__ = 'urllists'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    url_str = db.Column(db.String(100), nullable=False)

applications/login/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, ValidationError
from models import User

# ログイン用入力クラス
class LoginForm(FlaskForm):
    username = StringField('ユーザー名：',
                           validators=[DataRequired('ユーザー名は必須入力です')])
    password = PasswordField('パスワード: ',
                             validators=[Length(1, 10,
                                    'パスワードの長さは4文字以上10文字以内です')])
    submit = SubmitField('ログイン')

class SignUpForm(LoginForm):
    submit = SubmitField('サインアップ')
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('そのユーザー名は既に使用されています')

applications/redirect/forms.py
from flask_wtf import FlaskForm
from flask import session
from wtforms import StringField, TextAreaField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, ValidationError
from models import URLList
from urllib.parse import urlparse
import urllib.request, urllib.error

class InputForm(FlaskForm):
    def url_validator(self, url):
        try:
            response = urllib.request.urlopen(url.data)
        except urllib.error.HTTPError as e:
            raise ValidationError('HTTPError')
        except urllib.error.URLError as e:
            raise ValidationError('URLError')
        except :
            pass
    def url_parse(self, url):
        result = urlparse(url.data)
        check = len(result.scheme)
        if check < 1:
            raise ValidationError('URLが有効ではありません')

    url = StringField('URL名：',
                           validators=[DataRequired('必須入力です')\
                           , url_validator, url_parse])
    submit = SubmitField('発行')

app.py
from flask import Flask, render_template, abort, redirect, url_for
from flask_migrate import Migrate
from models import db, User, URLList

from flask_login import LoginManager
from flask_login import login_user, logout_user, login_required

#blueprint
from applications.login.views import login_bp
from applications.redirect.views import redirect_bp


app = Flask(__name__)

# DB
app.config.from_object("config.Config")
db.init_app(app)
migrate = Migrate(app, db)

# login設定
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_message = "認証していません：ログインしてください"
login_manager.login_view = 'login_app.login'

# Blueprint
app.register_blueprint(login_bp)
app.register_blueprint(redirect_bp)

@app.route('/')
def index():
    return redirect(url_for("redirect_app.input"), code=301)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

from errorhandler import *

if __name__ == "__main__":
    app.run()

applications/login/views.py
from flask import Blueprint, render_template
from models import db, User

from flask_login import LoginManager
from flask import Blueprint, render_template, redirect, url_for, flash
from applications.login.forms import LoginForm, SignUpForm
from flask_login import login_user, logout_user, login_required

#Blueprint
login_bp = Blueprint('login_app', __name__, url_prefix="/applications/login")

@login_bp.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username = username).first()
        if user is not None and user.check_password(password):
            login_user(user)
            return redirect(url_for("index"))
        flash("認証不備です")
    return render_template("login/login_form.html", form=form)

@login_bp.route("/register", methods=["GET", "POST"])
def register():
    # Formインスタンス生成
    form = SignUpForm()
    if form.validate_on_submit():
        # データ入力取得
        username = form.username.data
        password = form.password.data
        # モデルを生成
        user = User(username=username)
        # パスワードハッシュ化 model内の関数 user.の
        user.set_password(password)
        # 登録処理
        db.session.add(user)
        db.session.commit()
        # フラッシュメッセージ
        flash("ユーザー登録しました")
        # 画面遷移
        return redirect(url_for("login_app.login"))
    # GET時
    # 画面遷移
    return render_template("login/register_form.html", form=form)

applications/redirect/views.py
from flask import Flask, render_template, abort, send_file, redirect, url_for, flash
from flask import session, Blueprint
from datetime import timedelta
from flask_migrate import Migrate
from models import db, URLList
from bs4 import BeautifulSoup
from applications.redirect.forms import InputForm
import urllib.request, urllib.error
import os

from flask_login import LoginManager
from flask_login import login_user, logout_user, login_required

# Blueprint
redirect_bp = Blueprint('redirect_app', __name__, url_prefix="/applications/redirect")

# URLタイトル取得関数
def url_title_get(url):
    response = urllib.request.urlopen(url)
    parse_html = BeautifulSoup(response, "html.parser")
    title = parse_html.title.string
    return title

# URL取得関数
def url_get(id):
    urls = URLList.query.filter_by(id=id).first()
    urlstr = urls.url_str
    if urlstr == None:
        return redirect(url_for("redirect_app.input"), code=301)
    else:
        return urlstr

# ID取得関数 要素数カウント
def urlid_get():
    count = URLList.query.count()
    getid = count
    if getid == None:
        return redirect(url_for("redirect_app.input"), code=301)
    else:
        return getid

# 短縮URL変換関数
def url_change(id):
    urlstr = ("http://127.0.0.1:5000/applications/redirect/redirect/"+str(id))
    return urlstr

@redirect_bp.route('/input', methods=['GET','POST'])
@login_required
def input():
    form = InputForm()
    session['url'] = None
    if form.validate_on_submit():
        url_str = form.url.data
        urls = URLList(url_str=url_str)
        session['url'] = url_str
        db.session.add(urls)
        db.session.commit()
        flash("URL登録完了")
        return redirect(url_for("redirect_app.download_api"), code=301)
    return render_template("redirect/home.html", form=form)

@redirect_bp.route('/redirectgo')
def redirect_func():
    url = session['url']
    if url == None:
        return redirect(url_for("redirect_app.input"))
    else:
        return redirect(url, code=301)

@redirect_bp.route('/redirect/<int:id>')
def id_redirect(id):
    url = url_get(id)
    return redirect(url, code=301)

@redirect_bp.route("/download", methods=["GET", 'POST'])
@login_required
def download_api():
    os.remove("short_url.txt")
    with open('short_url.txt', 'w') as f:
        id = urlid_get()
        str = url_get(id)
        title = url_title_get(str)
        short_url = url_change(id)
        f.write("タイトル:"+title)
        f.write("\n")
        f.write("URL:"+"\n")
        f.write(short_url+"\n")
        pass
    filepath = "./short_url.txt"
    filename = os.path.basename(filepath)
    sd = send_file(filepath, as_attachment=True, mimetype='text/plain')
    return sd

templates/base.html
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="../static/dist/output.css" rel="stylesheet" />
    <title>{% block title %}
      title
    {% endblock %}</title>
  </head>
  <body>
    {% block header %}
      header
    {% endblock %}
    {% block content %}
      <br />
      content
    {% endblock %}
    {% block footer %}
      <br />
      <a href="{{url_for("index")}}">indexへ</a>
    {% endblock %}
  </body>
</html>

templates/base2.html
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="../../static/dist/output.css" rel="stylesheet" />
    <title>{% block title %}
      title
    {% endblock %}</title>
  </head>
  <body class="bg-gray-50">
    {% block header %}
      
    {% endblock %}
    {% block content %}
      <br />
      content
    {% endblock %}
    {% block footer %}
      <br />
      <a href="{{url_for("index")}}">indexへ</a>
    {% endblock %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}
<title>mahhas</title>
{% endblock %}
{% block header %}

{% endblock %}
{% block content %}

{% endblock %}
{% block footer %}
  <a href="{{url_for("index")}}">index</a>
{% endblock %}

templates/login/_formhelpers.html
{% macro render_field(field, class='') %}
    <dt>{{ field.label }}</dt>
    <dd>{{ field(class=class, **kwargs)|safe }}</dd>
    {% if field.errors %}
    <ul class="text-danger">
        {% for error in field.errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endmacro %}

templates/login/login_form.html
{% extends "base.html" %}
{% block title %}
  ログイン画面
{% endblock %}
{% block content %}
  <div>
      <h1 class="my-4">ログイン</h1>
      {% from "login/_formhelpers.html" import render_field %}
      <form method="POST" action="{{ url_for('login_app.login') }}" novalidate>
          {{ form.hidden_tag() }}
          {{ render_field(form.username, class="form-control") }}
          {{ render_field(form.password, class="form-control") }}
          <br>
          <!-- ▼▼▼▼▼ flashメッセージ ▼▼▼▼▼ -->
          {% for message in get_flashed_messages() %}
          <div class="alert alert-info">
              {{ message }}
          </div>
          {% endfor %}
          <!-- ▲▲▲▲▲ flashメッセージ ▲▲▲▲▲ -->
          {{ form.submit(class="btn btn-primary") }}
      </form>
      <p class="my-3">
          アカウントをお持ちでない場合は、
          <a href="{{url_for("login_app.register")}}">こちら</a>
          から登録してください。
      </p>
  </div>
{% endblock %}

templates/login/register_form.html
{% extends "base.html" %}
{% block title %}
  アカウント登録
{% endblock %}
{% block content %}
  <div class="container">
      <h1 class="my-4">サインアップ</h1>
      {% from "login/_formhelpers.html" import render_field %}
      <form method="POST" action="{{ url_for('login_app.register') }}" novalidate>
          {{ form.hidden_tag() }}
          {{ render_field(form.username, class="form-control") }}
          {{ render_field(form.password, class="form-control") }}
          <br>
          {{ form.submit(class="btn btn-primary") }}
      </form>
      <p class="my-3">すでにアカウントをお持ちの場合は、
          <a href="{{ url_for('login_app.login') }}">こちら</a>
          からログインしてください。
      </p>
  </div>
{% endblock %}

templates/redirect/_formhelpers.html
{% macro render_field(field, class='') %}
    <dt>{{ field.label }}</dt>
    <dd>{{ field(class=class, **kwargs)|safe }}</dd>
    {% if field.errors %}
    <ul class="text-danger">
        {% for error in field.errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endmacro %}

templates/redirect/home.html
{% extends "base2.html" %}
{% block content %}
<link href="../../static/form_stylesheet.css" rel="stylesheet" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gloock&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Kaisei+Tokumin&display=swap" rel="stylesheet">
  <div>
      <div class="flex items-center justify-center h-max py-28">
        <div class="flex float-left pr-5 px-4 py-3 rounded-md shadow-md
        -inset-1 bg-gradient-to-r from-pink-300 to-purple-400 blur-md opacity-75 ">
          <img src="../../static/img/2.jpg" class="h-24 rounded-full" />
          <a class="flex items-center pl-3 text-5xl font-gloock text-blue-900">ShortURL</a>
          <a class="flex items-center text-4xl font-kaisei font-bold text-blue-900">変換</a>
        </div>

      </div>
      <h1 class="bg-yellow-400 text-white uppercase tracking-wide px-6 py-2"
      >URL入力</h1>
      {% from "redirect/_formhelpers.html" import render_field %}
      <form method="POST" action="{{ url_for("redirect_app.input") }}" novalidate class=
      "bg-yellow-100 text-black uppercase tracking-wide px-6 py-6 pb-8 shadow-sm">
          <div class="mb-3 font-bold">
            {{ form.hidden_tag() }}
            {{ render_field(form.url, class="form-control") }}
          </div>
          <!-- ▼▼▼▼▼ flashメッセージ ▼▼▼▼▼ -->
          {% for message in get_flashed_messages() %}
          <div class="alert alert-info">
              {{ message }}
          </div>
          {% endfor %}
          <!-- ▲▲▲▲▲ flashメッセージ ▲▲▲▲▲ -->
          <div class="">
            <p class="float-left">
              {{ form.submit(class="btn btn-primary") }}
            </p>
            <a href="{{url_for("redirect_app.redirect_func")}}" class="font-kaisei float-left pl-3">
              GO
            </a>
          </div>
      </form>
      <br>

  </div>
{% endblock %}
{% block footer %}

{% endblock %}